apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: secretstore-sample
  target:
    name: postgres-credentials-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: postgres-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: postgres-credentials
        property: password
  refreshInterval: 100h
