apiVersion: externalsecrets.k8s.io/v1alpha1
kind: ExternalSecret
metadata:
  name: postgres-credentials-secret
  namespace: dev
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: postgres-credentials-secret
  data:
    - secretKey: username
      remoteRef:
        key: postgres-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: postgres-credentials
        property: password
