apiVersion: apps/v1
kind: Deployment
metadata:
  name: projecti-deployment
  labels:
    app: projecti
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projecti
  template:
    metadata:
      labels:
        app: projecti
    spec:
      containers:
        - name: projecti
          image: klimentchakarovski/projecti
          ports:
            - containerPort: 3000
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials-secret
                  key: password
