apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgre-credentials
  namespace: projecti
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store  
    kind: SecretStore
  target:
    name: postgres-credentials
  data:
    - secretKey: username
      remoteRef:
        key: postgres-credentials  
        property: username       
    - secretKey: password
      remoteRef:
        key: postgres-credentials  
        property: password
