apiVersion: v1
kind: Service
metadata:
  name: projecti-service
  namespace: projecti
spec:
  type: NodePort
  selector:
    app: projecti
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
