---
- name: Install required packages on Amazon Linux 2023
  hosts: all
  become: yes
  tasks:
    - name: Update package index
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install Python 3 and pip
      ansible.builtin.dnf:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Git
      ansible.builtin.dnf:
        name: git
        state: present

    - name: Copy requirements.txt to the remote machine
      ansible.builtin.copy:
        src: "requirements.txt"
        dest: "/home/ec2-user/requirements.txt"

    - name: Check if requirements.txt exists on remote machine
      ansible.builtin.stat:
        path: "/home/ec2-user/requirements.txt"
      register: result

    - name: Show result of file check
      ansible.builtin.debug:
        var: result

    - name: Install dependencies from requirements file
      ansible.builtin.pip:
        requirements: "/home/ec2-user/requirements.txt"
        executable: pip3
      when: result.stat.exists
